import { Escuderia } from '../types/escuderia';

/**
 * ESCUDERIAS_DATA
 * 
 * Listado estático de escuderías disponibles para el inicio de una nueva partida.
 * Los datos técnicos definen la dificultad inicial y el potencial del equipo.
 */
export const ESCUDERIAS_DATA: Escuderia[] = [
    {
        id: 1,
        nombre: "Oracle Red Bull Racing",
        imagen: "assets/images/teams/red-bull.png",
        presupuesto: 145.00,
        aerodinamica: 76,
        motor: 72,
        durabilidad: 12,
        tunelViento: 3,
        bancoPruebas: 2,
        escuelaPilotos: 3,
        aerodinamicaCosto: 0,
        motorCosto: 0,
        durabilidadCosto: 0
    },
    {
        id: 2,
        nombre: "Mercedes-AMG PETRONAS",
        imagen: "assets/images/teams/mercedes.png",
        presupuesto: 140.00,
        aerodinamica: 72,
        motor: 78,
        durabilidad: 16,
        tunelViento: 3,
        bancoPruebas: 3,
        escuelaPilotos: 2,
        aerodinamicaCosto: 0,
        motorCosto: 0,
        durabilidadCosto: 0
    },
    {
        id: 3,
        nombre: "Scuderia Ferrari HP",
        imagen: "assets/images/teams/ferrari.png",
        presupuesto: 142.00,
        aerodinamica: 74,
        motor: 79,
        durabilidad: 14,
        tunelViento: 2,
        bancoPruebas: 3,
        escuelaPilotos: 3,
        aerodinamicaCosto: 0,
        motorCosto: 0,
        durabilidadCosto: 0
    },
    {
        id: 4,
        nombre: "McLaren Formula 1",
        imagen: "assets/images/teams/mclaren.png",
        presupuesto: 135.00,
        aerodinamica: 80,
        motor: 77,
        durabilidad: 17,
        tunelViento: 3,
        bancoPruebas: 2,
        escuelaPilotos: 2,
        aerodinamicaCosto: 0,
        motorCosto: 0,
        durabilidadCosto: 0
    },
    {
        id: 5,
        nombre: "Aston Martin Aramco",
        imagen: "assets/images/teams/aston-martin.png",
        presupuesto: 125.00,
        aerodinamica: 73,
        motor: 75,
        durabilidad: 13,
        tunelViento: 3,
        bancoPruebas: 2,
        escuelaPilotos: 1,
        aerodinamicaCosto: 0,
        motorCosto: 0,
        durabilidadCosto: 0
    },
    {
        id: 6,
        nombre: "Alpine F1 Team",
        imagen: "assets/images/teams/alpine.png",
        presupuesto: 110.00,
        aerodinamica: 65,
        motor: 68,
        durabilidad: 10,
        tunelViento: 2,
        bancoPruebas: 2,
        escuelaPilotos: 3,
        aerodinamicaCosto: 0,
        motorCosto: 0,
        durabilidadCosto: 0
    },
    {
        id: 7,
        nombre: "Williams Racing",
        imagen: "assets/images/teams/williams.png",
        presupuesto: 95.00,
        aerodinamica: 62,
        motor: 76,
        durabilidad: 15,
        tunelViento: 1,
        bancoPruebas: 2,
        escuelaPilotos: 2,
        aerodinamicaCosto: 0,
        motorCosto: 0,
        durabilidadCosto: 0
    },
    {
        id: 8,
        nombre: "Racing Bulls (VCARB)",
        imagen: "assets/images/teams/racing-bulls.png",
        presupuesto: 85.00,
        aerodinamica: 68,
        motor: 71,
        durabilidad: 12,
        tunelViento: 2,
        bancoPruebas: 1,
        escuelaPilotos: 3,
        aerodinamicaCosto: 0,
        motorCosto: 0,
        durabilidadCosto: 0
    },
    {
        id: 9,
        nombre: "Audi F1 Team",
        imagen: "assets/images/teams/audi.png",
        presupuesto: 130.00,
        aerodinamica: 66,
        motor: 74,
        durabilidad: 11,
        tunelViento: 2,
        bancoPruebas: 3,
        escuelaPilotos: 2,
        aerodinamicaCosto: 0,
        motorCosto: 0,
        durabilidadCosto: 0
    },
    {
        id: 10,
        nombre: "MoneyGram Haas F1 Team",
        imagen: "assets/images/teams/haas.png",
        presupuesto: 80.00,
        aerodinamica: 64,
        motor: 75,
        durabilidad: 16,
        tunelViento: 1,
        bancoPruebas: 1,
        escuelaPilotos: 1,
        aerodinamicaCosto: 0,
        motorCosto: 0,
        durabilidadCosto: 0
    },
    {
        id: 11,
        nombre: "Cadillac Andretti F1",
        imagen: "assets/images/teams/cadilac.png",
        presupuesto: 120.00,
        aerodinamica: 60,
        motor: 70,
        durabilidad: 9,
        tunelViento: 2,
        bancoPruebas: 2,
        escuelaPilotos: 1,
        aerodinamicaCosto: 0,
        motorCosto: 0,
        durabilidadCosto: 0
    }
];
